Removing kruft; adding Vundle; polish initialize
Apparently I played around with emacsmode at some point.  We'll just go
ahead and call that experiment concluded.  Removing the files.

Removing an old git plugin - using tpope's fugitive now.

Removing an old syntax-file-in-progress.

No more .vimrc in the repo (it's .gitignored now) - there's a
.vimrc.NoVundle and a .vimrc.Vundle.  The 'initialize' script is
responsible for symlinking the appropriate config to ".vimrc", for
syncenv() to put in place.

Exiting from 'initialize' on FATALs.

'initialize' now pulls/clones, and bootstraps Vundle for me.

diff --git a/initialize b/initialize
--- a/initialize
+++ b/initialize
@@ -17,7 +17,8 @@ Git=$(which git 2> /dev/null)
 if [[ $? -ne 0 ]]
 then
     Git="NO_GIT"
-    echo "WARNING: No git found in your path - will be unable to complete the setup."
+    echo "WARNING: No git found in your path."
+    echo "WARNING: Will be unable to complete the git dependent portion of the setup."
     echo -n "Continue? [y/N] "
     read yN
     if [[ $yN =~ ^y ]]
@@ -40,12 +41,14 @@ then
         ln -s .vimrc.NoVundle .vimrc
     else
         echo "FATAL: No .vimrc source candidate (.vimrc.NoVundle) available in $WorkingDir"
+        exit 1
     fi
 elif [[ -f ".vimrc.Vundle" ]]
 then
     ln -s .vimrc.Vundle .vimrc
 else
     echo "FATAL: No .vimrc source candidate (.vimrc.Vundle) available in $WorkingDir"
+    exit 1
 fi
 
 # Now get things started.
@@ -56,7 +59,23 @@ if [[ -d ${HOME}/.vim ]]
 then
     if [[ ${Git:-NO_GIT} != "NO_GIT" ]]
     then
-        $Git clone https://github.com/gmarik/Vundle.vim.git ${HOME}/.vim/bundle/Vundle.vim
+        BundleDir="${HOME}/.vim/bundle/Vundle.vim"
+        BundleCount=$(/bin/ls -A1 $BundleDir | wc -l)
+        if [[ -d $BundleDir && $BundleCount -gt 0 ]]
+        then
+            cd $BundleDir
+            $Git pull --rebase
+        else
+            $Git clone https://github.com/gmarik/Vundle.vim.git ${HOME}/.vim/bundle/Vundle.vim
+        fi
+
+        Vim=$(which vim)
+        if [[ $? -eq 0 ]]
+        then
+            $Vim +PluginInstall +qall
+        else
+            echo "No vim found - unable to initialize Vundle plugins"
+        fi
     else
         echo "No git found - skipping Vundle setup."
     fi
